blacklisted_items:
    - Q86995636  # Scientific articles
    - Q318  # Galaxy
    - Q4167410  # disambiguation page
    - Q4167836  # Wikimedia Category
    - Q11266439  # Wikimedia Template
    - Q15184295  # Module pages
    - Q13442814  # Journal article
    - Q13406463  # Wikimedia List

blacklisted_properties:
    - P31
    - P279
    - P373  # Commons category
    - P910  # Topic's main category
    # Commons media data type:
    - P10
    - P14
    - P15
    - P18
    - P41
    - P51
    - P94
    - P109
    - P117
    - P154
    - P158
    - P181
    - P207
    - P242
    - P367
    - P368
    - P443
    - P491
    - P692
    - P948
    - P989
    - P990
    - P996
    - P1442
    - P1543
    - P1621
    - P1766
    - P1801
    - P1846
    - P1943
    - P1944
    - P2343
    - P2425
    - P2713
    - P2716
    - P2910
    - P2919
    - P3030
    - P3311
    - P3383
    - P3451
    - P4004
    - P4291
    - P4640
    - P4896
    - P5252
    - P5555
    - P5775
    - P5962
    - P6655
    - P6685
    - P6802
    - P7009
    - P7407
    - P7415
    - P7417
    - P7418
    - P7420
    - P7457
    # End of Commons media data type:

data_storage_path:
    'data/'

user_agent:
    'wikidata-reference-island (https://github.com/wmde/reference-island) requests python'

wdqs_url:
    'https://query.wikidata.org/sparql'